// <auto-generated />
namespace MySmartHome.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class version_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201708300601033_version_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
